<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open MenuAll ItemsAboutLogoutReset App _5a4565</name>
   <tag></tag>
   <elementGuidId>09312d73-f9c1-419b-889e-664109cd5467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#page_wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#page_wrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec5d21db-6f05-4329-a4d5-95a3862f44c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page_wrapper</value>
      <webElementGuid>9adaf055-69ec-42b0-ab72-cb9854104659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page_wrapper</value>
      <webElementGuid>7b7728db-e974-48a7-b13a-d08452869953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open MenuAll ItemsAboutLogoutReset App StateClose MenuSwag LabsYour CartQTYDescriptionContinue ShoppingCheckoutTwitterFacebookLinkedIn© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy</value>
      <webElementGuid>84337d5f-4d99-4141-9d6d-d9b963ae627a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)</value>
      <webElementGuid>c99ac1fc-6839-403d-bf58-c1ea97a594d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']</value>
      <webElementGuid>d45e5720-ec1f-4cb3-9dc6-f5789cad49db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>82c27117-f75b-464c-a9bd-a8589d4c0ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>f167c218-51f1-456c-b158-4a211225a3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'page_wrapper' and (text() = 'Open MenuAll ItemsAboutLogoutReset App StateClose MenuSwag LabsYour CartQTYDescriptionContinue ShoppingCheckoutTwitterFacebookLinkedIn© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy' or . = 'Open MenuAll ItemsAboutLogoutReset App StateClose MenuSwag LabsYour CartQTYDescriptionContinue ShoppingCheckoutTwitterFacebookLinkedIn© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy')]</value>
      <webElementGuid>8a174caa-bdcd-4b3a-9223-ad8dfada335c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
